import { MigrationInterface, QueryRunner } from "typeorm";

export class makeDatesAutoGenerated1657257452056 implements MigrationInterface {
    name = 'makeDatesAutoGenerated1657257452056'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "message" ALTER COLUMN "createdAt" SET DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "message" ALTER COLUMN "createdAt" DROP DEFAULT`);
    }

}
